// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8_IXdbfi-k7cBnksNBHepiHjDfDg7Tg',
    appId: '1:674387350242:web:50a03a999bff39621f84bb',
    messagingSenderId: '674387350242',
    projectId: 'gheras-app-bde92',
    authDomain: 'gheras-app-bde92.firebaseapp.com',
    storageBucket: 'gheras-app-bde92.firebasestorage.app',
    measurementId: 'G-WKQL65R1CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8qTf_l-28rFQoH5N1f2F9xE-ogDFnpFM',
    appId: '1:674387350242:android:f9d611aa6d9ac25b1f84bb',
    messagingSenderId: '674387350242',
    projectId: 'gheras-app-bde92',
    storageBucket: 'gheras-app-bde92.firebasestorage.app',
  );

}